### ISSUE TITLE
Not getting notif

### ISSUE THREAD

**Issue by darkman7hr** [johman10/ntfy-browser#1]
I use chromium on linux and it doesn't display any push messages.
server is https://jezgra.net:8444.

Also, I've hardcoded topic and server as it cannot save options.

Any updates? :)

**Comment by johman10** [comment]
@darkman7hr this project is still under development so I can't promise that it fully works yet. If it fails to save it might have to do with authorization, please make sure you use a valid token for you selfhosted server.

**Comment by darkman7hr** [comment]
found it.. put token but still. Settings cannot be saved.
https://ibb.co/5hj5jws

**Comment by johman10** [comment]
Right, that shouldn't really happen. Currently I also don't really log the error anywhere. :see_no_evil: 

But it's most likely that you didn't allow the extension to write to chrome storage. [This is the line you reach](https://github.com/johman10/ntfy-browser/blob/69b009b6901f43b831d64ad033d1271c822e44a0/src/options.tsx#L99), which means something in that Promise is failing. Hard to know exactly what fails without more information.

**Comment by darkman7hr** [comment]
I checked all options, everything is allowed.

In errors I get (I don't know if it's related, not much of a coder)

TypeError: Cannot read properties of undefined (reading 'getTopicQuery')
Context
js/background.js


Stack Trace
js/background.js:1 (anonymous function)

`(()=>{var e={8136:function(e,r,s){"use strict";var t=this&&this.__importDefault||function(e){return e&&e.__esModule?e:{default:e}};Object.defineProperty(r,"__esModule",{value:!0});const n=s(3150),i=s(8159),a=t(s(7977)),o=t(s(4845)),g=s(307),m=t(s(9415)),c=t(s(9539)),l=new a.default,A=new o.default(l),u=new m.default,x=new c.default(A);function d(e,r){console.error(e),r&&u.publish(crypto.randomUUID(),{type:"basic",iconUrl:"../ntfy-512.png",title:n.i18n.getMessage("connectFailureNotificationTitle",r),message:n.i18n.getMessage("connectFailureNotificationMessage"),isClickable:!0},n.runtime.getURL("options.html"))}n.runtime.onMessage.addListener((e=>"configSave"===e.event?(x.unsubscribeAll(),x.subscribeAll().then((e=>{const r=e.filter((e=>e.event===i.EventResponseType.CONNECTION_FAILED));if(r.length){const e=r.map((e=>e.topicConfig.name)).join(", ");d(new Error(`[ntfy-browser] Unable to connect to ${e}`),e)}return e})).catch((e=>{throw d(e),e}))):((0,g.assertNever)(e.event),Promise.resolve([])))),u.startClickListener(),A.startClickListener(),x.subscribeAll().catch(d)},8159:(e,r,s)=>{"use strict";var t;Object.defineProperty(r,"__esModule",{value:!0}),r.EventResponseType=void 0,s(3553),(t=r.EventResponseType||(r.EventResponseType={})).CONNECTION_SUCCESS="connectionSuccess",t.CONNECTION_FAILED="connectionFailed"},7977:(e,r,s)=>{"use strict";Object.defineProperty(r,"__esModule",{value:!0});const t=s(3150);class n{constructor(){if(this.currentNumber=0,n.instance)return n.instance;n.instance=this}reset(){return this.currentNumber=0,this.setText()}lower(){return this.currentNumber?(this.currentNumber-=1,this.setText()):Promise.resolve()}higher(){return this.currentNumber+=1,this.setText()}setText(){let e=this.currentNumber.toString();return this.currentNumber<1&&(e=""),t.action.setBadgeText({text:e})}}n.instance=null,r.default=n},9415:function(e,r,s){"use strict";var t=this&&this.__awaiter||function(e,r,s,t){return new(s||(s=Promise))((function(n,i){function a(e){try{g(t.next(e))}catch(e){i(e)}}function o(e){try{g(t.throw(e))}catch(e){i(e)}}function g(e){var r;e.done?n(e.value):(r=e.value,r instanceof s?r:new s((function(e){e(r)}))).then(a,o)}g((t=t.apply(e,r||[])).next())}))};Object.defineProperty(r,"__esModule",{value:!0});const n=s(3150);class i{constructor(){if(this.notificationCache=[],i.instance)return i.instance;i.instance=this}getNotificationById(e){return this.notificationCache.find((r=>r.id===e))}addToCache(e){this.notificationCache.push(e)}onClick(e){const r=this.getNotificationById(e);return r&&r.isClickable?n.tabs.create({url:r.click}):Promise.resolve()}publish(e,r,s){return t(this,void 0,void 0,(function*(){yield n.notifications.create(e,r),this.addToCache(Object.assign(Object.assign({},r),{id:e,click:s}))}))}startClickListener(){n.notifications.onClicked.addListener((e=>this.onClick(e)))}}i.instance=null,r.default=i},4845:function(e,r,s){"use strict";var t=this&&this.__awaiter||function(e,r,s,t){return new(s||(s=Promise))((function(n,i){function a(e){try{g(t.next(e))}catch(e){i(e)}}function o(e){try{g(t.throw(e))}catch(e){i(e)}}function g(e){var r;e.done?n(e.value):(r=e.value,r instanceof s?r:new s((function(e){e(r)}))).then(a,o)}g((t=t.apply(e,r||[])).next())}))};Object.defineProperty(r,"__esModule",{value:!0});const n=s(3150);class i{constructor(e){if(this.badgeNumberManager=e,this.notificationCache=[],i.instance)return i.instance;i.instance=this}getNotificationById(e){return this.notificationCache.find((r=>r.id===e))}addToCache(e){this.notificationCache.push(e)}onClick(e){var r,s;const t=this.getNotificationById(e);return t&&(t.click||(null===(r=t.attachment)||void 0===r?void 0:r.url))?n.tabs.create({url:t.click||(null===(s=t.attachment)||void 0===s?void 0:s.url)}):Promise.resolve()}getBaseNotificationOptions(e){let r=(e.priority||0)-3;return r<0&&(r=0),{iconUrl:"../ntfy-512.png",title:e.title||e.topic,message:e.message||"",priority:r,eventTime:e.time,isClickable:!!e.click}}getNotificationOptions(e){return e.attachment&&e.attachment.type.startsWith("image/")?Object.assign({type:"image",imageUrl:e.attachment.url},this.getBaseNotificationOptions(e)):Object.assign({type:"basic"},this.getBaseNotificationOptions(e))}publish(e){return t(this,void 0,void 0,(function*(){yield n.notifications.create(e.id,this.getNotificationOptions(e)),this.addToCache(e),this.badgeNumberManager.higher()}))}startClickListener(){n.notifications.onClicked.addListener((e=>this.onClick(e).then((()=>{this.badgeNumberManager.lower()}))))}}r.default=i},9539:function(e,r,s){"use strict";var t=this&&this.__awaiter||function(e,r,s,t){return new(s||(s=Promise))((function(n,i){function a(e){try{g(t.next(e))}catch(e){i(e)}}function o(e){try{g(t.throw(e))}catch(e){i(e)}}function g(e){var r;e.done?n(e.value):(r=e.value,r instanceof s?r:new s((function(e){e(r)}))).then(a,o)}g((t=t.apply(e,r||[])).next())}))};Object.defineProperty(r,"__esModule",{value:!0});const n=s(3150),i=s(8159),a=s(3553);class o{constructor(e){if(this.ntfyNotificationManager=e,this.eventSources=[],o.instance)return o.instance;o.instance=this,this.ntfyNotificationManager=e}unsubscribe(e){e.close(),this.eventSources=this.eventSources.filter((r=>r.url!==e.url))}getTopicConfigs(){return t(this,void 0,void 0,(function*(){return(yield n.storage.sync.get({[a.BROWSER_TOPIC_CONFIGS_STORAGE_KEY]:{}}))[a.BROWSER_TOPIC_CONFIGS_STORAGE_KEY]}))}getTopicQuery(e){if(!e)return"";const r=`Bearer ${e}`,s=window.btoa(r).replace(/=+$/,"");return`?${new URLSearchParams({auth:s}).toString()}`}subscribe(e){return new Promise((r=>{const s=this.getTopicQuery(e.token),t=new URL(`${e.name}/sse${s}`,e.hostname),n=new EventSource(t);n.onmessage=e=>{const r=JSON.parse(e.data);this.ntfyNotificationManager.publish(r)},n.onerror=()=>{this.unsubscribe(n),r({event:i.EventResponseType.CONNECTION_FAILED,topicConfig:e})},n.onopen=()=>{this.eventSources.includes(n)||(this.eventSources=[...this.eventSources,n]),r({event:i.EventResponseType.CONNECTION_SUCCESS,topicConfig:e})}}))}subscribeAll(){return t(this,void 0,void 0,(function*(){const e=yield this.getTopicConfigs(),r=Object.values(e).map(this.subscribe);return Promise.all(r)}))}unsubscribeAll(){this.eventSources.forEach(this.unsubscribe)}}r.default=o},3553:(e,r)=>{"use strict";Object.defineProperty(r,"__esModule",{value:!0}),r.BROWSER_TOPIC_CONFIGS_STORAGE_KEY=void 0,r.BROWSER_TOPIC_CONFIGS_STORAGE_KEY="topicConfigs"},307:(e,r)=>{"use strict";Object.defineProperty(r,"__esModule",{value:!0}),r.assertNever=void 0,r.assertNever=function(e){throw new Error(`Unhandled discriminated union member: ${JSON.stringify(e)}`)}},3150:function(e,r){var s,t;"undefined"!=typeof globalThis?globalThis:"undefined"!=typeof self&&self,s=function(e){"use strict";if(!globalThis.chrome?.runtime?.id)throw new Error("This script should only be loaded in a browser extension.");if(void 0===globalThis.browser||Object.getPrototypeOf(globalThis.browser)!==Object.prototype){const r="The message port closed before a response was received.",s=e=>{const s={alarms:{clear:{minArgs:0,maxArgs:1},clearAll:{minArgs:0,maxArgs:0},get:{minArgs:0,maxArgs:1},getAll:{minArgs:0,maxArgs:0}},bookmarks:{create:{minArgs:1,maxArgs:1},get:{minArgs:1,maxArgs:1},getChildren:{minArgs:1,maxArgs:1},getRecent:{minArgs:1,maxArgs:1},getSubTree:{minArgs:1,maxArgs:1},getTree:{minArgs:0,maxArgs:0},move:{minArgs:2,maxArgs:2},remove:{minArgs:1,maxArgs:1},removeTree:{minArgs:1,maxArgs:1},search:{minArgs:1,maxArgs:1},update:{minArgs:2,maxArgs:2}},browserAction:{disable:{minArgs:0,maxArgs:1,fallbackToNoCallback:!0},enable:{minArgs:0,maxArgs:1,fallbackToNoCallback:!0},getBadgeBackgroundColor:{minArgs:1,maxArgs:1},getBadgeText:{minArgs:1,maxArgs:1},getPopup:{minArgs:1,maxArgs:1},getTitle:{minArgs:1,maxArgs:1},openPopup:{minArgs:0,maxArgs:0},setBadgeBackgroundColor:{minArgs:1,maxArgs:1,fallbackToNoCallback:!0},setBadgeText:{minArgs:1,maxArgs:1,fallbackToNoCallback:!0},setIcon:{minArgs:1,maxArgs:1},setPopup:{minArgs:1,maxArgs:1,fallbackToNoCallback:!0},setTitle:{minArgs:1,maxArgs:1,fallbackToNoCallback:!0}},browsingData:{remove:{minArgs:2,maxArgs:2},removeCache:{minArgs:1,maxArgs:1},removeCookies:{minArgs:1,maxArgs:1},removeDownloads:{minArgs:1,maxArgs:1},removeFormData:{minArgs:1,maxArgs:1},removeHistory:{minArgs:1,maxArgs:1},removeLocalStorage:{minArgs:1,maxArgs:1},removePasswords:{minArgs:1,maxArgs:1},removePluginData:{minArgs:1,maxArgs:1},settings:{minArgs:0,maxArgs:0}},commands:{getAll:{minArgs:0,maxArgs:0}},contextMenus:{remove:{minArgs:1,maxArgs:1},removeAll:{minArgs:0,maxArgs:0},update:{minArgs:2,maxArgs:2}},cookies:{get:{minArgs:1,maxArgs:1},getAll:{minArgs:1,maxArgs:1},getAllCookieStores:{minArgs:0,maxArgs:0},remove:{minArgs:1,maxArgs:1},set:{minArgs:1,maxArgs:1}},devtools:{inspectedWindow:{eval:{minArgs:1,maxArgs:2,singleCallbackArg:!1}},panels:{create:{minArgs:3,maxArgs:3,singleCallbackArg:!0},elements:{createSidebarPane:{minArgs:1,maxArgs:1}}}},downloads:{cancel:{minArgs:1,maxArgs:1},download:{minArgs:1,maxArgs:1},erase:{minArgs:1,maxArgs:1},getFileIcon:{minArgs:1,maxArgs:2},open:{minArgs:1,maxArgs:1,fallbackToNoCallback:!0},pause:{minArgs:1,maxArgs:1},removeFile:{minArgs:1,maxArgs:1},resume:{minArgs:1,maxArgs:1},search:{minArgs:1,maxArgs:1},show:{minArgs:1,maxArgs:1,fallbackToNoCallback:!0}},extension:{isAllowedFileSchemeAccess:{minArgs:0,maxArgs:0},isAllowedIncognitoAccess:{minArgs:0,maxArgs:0}},history:{addUrl:{minArgs:1,maxArgs:1},deleteAll:{minArgs:0,maxArgs:0},deleteRange:{minArgs:1,maxArgs:1},deleteUrl:{minArgs:1,maxArgs:1},getVisits:{minArgs:1,maxArgs:1},search:{minArgs:1,maxArgs:1}},i18n:{detectLanguage:{minArgs:1,maxArgs:1},getAcceptLanguages:{minArgs:0,maxArgs:0}},identity:{launchWebAuthFlow:{minArgs:1,maxArgs:1}},idle:{queryState:{minArgs:1,maxArgs:1}},management:{get:{minArgs:1,maxArgs:1},getAll:{minArgs:0,maxArgs:0},getSelf:{minArgs:0,maxArgs:0},setEnabled:{minArgs:2,maxArgs:2},uninstallSelf:{minArgs:0,maxArgs:1}},notifications:{clear:{minArgs:1,maxArgs:1},create:{minArgs:1,maxArgs:2},getAll:{minArgs:0,maxArgs:0},getPermissionLevel:{minArgs:0,maxArgs:0},update:{minArgs:2,maxArgs:2}},pageAction:{getPopup:{minArgs:1,maxArgs:1},getTitle:{minArgs:1,maxArgs:1},hide:{minArgs:1,maxArgs:1,fallbackToNoCallback:!0},setIcon:{minArgs:1,maxArgs:1},setPopup:{minArgs:1,maxArgs:1,fallbackToNoCallback:!0},setTitle:{minArgs:1,maxArgs:1,fallbackToNoCallback:!0},show:{minArgs:1,maxArgs:1,fallbackToNoCallback:!0}},permissions:{contains:{minArgs:1,maxArgs:1},getAll:{minArgs:0,maxArgs:0},remove:{minArgs:1,maxArgs:1},request:{minArgs:1,maxArgs:1}},runtime:{getBackgroundPage:{minArgs:0,maxArgs:0},getPlatformInfo:{minArgs:0,maxArgs:0},openOptionsPage:{minArgs:0,maxArgs:0},requestUpdateCheck:{minArgs:0,maxArgs:0},sendMessage:{minArgs:1,maxArgs:3},sendNativeMessage:{minArgs:2,maxArgs:2},setUninstallURL:{minArgs:1,maxArgs:1}},sessions:{getDevices:{minArgs:0,maxArgs:1},getRecentlyClosed:{minArgs:0,maxArgs:1},restore:{minArgs:0,maxArgs:1}},storage:{local:{clear:{minArgs:0,maxArgs:0},get:{minArgs:0,maxArgs:1},getBytesInUse:{minArgs:0,maxArgs:1},remove:{minArgs:1,maxArgs:1},set:{minArgs:1,maxArgs:1}},managed:{get:{minArgs:0,maxArgs:1},getBytesInUse:{minArgs:0,maxArgs:1}},sync:{clear:{minArgs:0,maxArgs:0},get:{minArgs:0,maxArgs:1},getBytesInUse:{minArgs:0,maxArgs:1},remove:{minArgs:1,maxArgs:1},set:{minArgs:1,maxArgs:1}}},tabs:{captureVisibleTab:{minArgs:0,maxArgs:2},create:{minArgs:1,maxArgs:1},detectLanguage:{minArgs:0,maxArgs:1},discard:{minArgs:0,maxArgs:1},duplicate:{minArgs:1,maxArgs:1},executeScript:{minArgs:1,maxArgs:2},get:{minArgs:1,maxArgs:1},getCurrent:{minArgs:0,maxArgs:0},getZoom:{minArgs:0,maxArgs:1},getZoomSettings:{minArgs:0,maxArgs:1},goBack:{minArgs:0,maxArgs:1},goForward:{minArgs:0,maxArgs:1},highlight:{minArgs:1,maxArgs:1},insertCSS:{minArgs:1,maxArgs:2},move:{minArgs:2,maxArgs:2},query:{minArgs:1,maxArgs:1},reload:{minArgs:0,maxArgs:2},remove:{minArgs:1,maxArgs:1},removeCSS:{minArgs:1,maxArgs:2},sendMessage:{minArgs:2,maxArgs:3},setZoom:{minArgs:1,maxArgs:2},setZoomSettings:{minArgs:1,maxArgs:2},update:{minArgs:1,maxArgs:2}},topSites:{get:{minArgs:0,maxArgs:0}},webNavigation:{getAllFrames:{minArgs:1,maxArgs:1},getFrame:{minArgs:1,maxArgs:1}},webRequest:{handlerBehaviorChanged:{minArgs:0,maxArgs:0}},windows:{create:{minArgs:0,maxArgs:1},get:{minArgs:1,maxArgs:2},getAll:{minArgs:0,maxArgs:1},getCurrent:{minArgs:0,maxArgs:1},getLastFocused:{minArgs:0,maxArgs:1},remove:{minArgs:1,maxArgs:1},update:{minArgs:2,maxArgs:2}}};if(0===Object.keys(s).length)throw new Error("api-metadata.json has not been included in browser-polyfill");class t extends WeakMap{constructor(e,r){super(r),this.createItem=e}get(e){return this.has(e)||this.set(e,this.createItem(e)),super.get(e)}}const n=(r,s)=>(...t)=>{e.runtime.lastError?r.reject(new Error(e.runtime.lastError.message)):s.singleCallbackArg||t.length<=1&&!1!==s.singleCallbackArg?r.resolve(t[0]):r.resolve(t)},i=e=>1==e?"argument":"arguments",a=(e,r,s)=>new Proxy(r,{apply:(r,t,n)=>s.call(t,e,...n)});let o=Function.call.bind(Object.prototype.hasOwnProperty);const g=(e,r={},s={})=>{let t=Object.create(null),m={has:(r,s)=>s in e||s in t,get(m,c,l){if(c in t)return t[c];if(!(c in e))return;let A=e[c];if("function"==typeof A)if("function"==typeof r[c])A=a(e,e[c],r[c]);else if(o(s,c)){let r=((e,r)=>function(s,...t){if(t.length<r.minArgs)throw new Error(`Expected at least ${r.minArgs} ${i(r.minArgs)} for ${e}(), got ${t.length}`);if(t.length>r.maxArgs)throw new Error(`Expected at most ${r.maxArgs} ${i(r.maxArgs)} for ${e}(), got ${t.length}`);return new Promise(((i,a)=>{if(r.fallbackToNoCallback)try{s[e](...t,n({resolve:i,reject:a},r))}catch(n){console.warn(`${e} API method doesn't seem to support the callback parameter, falling back to call it without a callback: `,n),s[e](...t),r.fallbackToNoCallback=!1,r.noCallback=!0,i()}else r.noCallback?(s[e](...t),i()):s[e](...t,n({resolve:i,reject:a},r))}))})(c,s[c]);A=a(e,e[c],r)}else A=A.bind(e);else if("object"==typeof A&&null!==A&&(o(r,c)||o(s,c)))A=g(A,r[c],s[c]);else{if(!o(s,"*"))return Object.defineProperty(t,c,{configurable:!0,enumerable:!0,get:()=>e[c],set(r){e[c]=r}}),A;A=g(A,r[c],s["*"])}return t[c]=A,A},set:(r,s,n,i)=>(s in t?t[s]=n:e[s]=n,!0),defineProperty:(e,r,s)=>Reflect.defineProperty(t,r,s),deleteProperty:(e,r)=>Reflect.deleteProperty(t,r)},c=Object.create(e);return new Proxy(c,m)},m=e=>({addListener(r,s,...t){r.addListener(e.get(s),...t)},hasListener:(r,s)=>r.hasListener(e.get(s)),removeListener(r,s){r.removeListener(e.get(s))}}),c=new t((e=>"function"!=typeof e?e:function(r){const s=g(r,{},{getContent:{minArgs:0,maxArgs:0}});e(s)})),l=new t((e=>"function"!=typeof e?e:function(r,s,t){let n,i,a=!1,o=new Promise((e=>{n=function(r){a=!0,e(r)}}));try{i=e(r,s,n)}catch(e){i=Promise.reject(e)}const g=!0!==i&&((m=i)&&"object"==typeof m&&"function"==typeof m.then);var m;if(!0!==i&&!g&&!a)return!1;return(g?i:o).then((e=>{t(e)}),(e=>{let r;r=e&&(e instanceof Error||"string"==typeof e.message)?e.message:"An unexpected error occurred",t({__mozWebExtensionPolyfillReject__:!0,message:r})})).catch((e=>{console.error("Failed to send onMessage rejected reply",e)})),!0})),A=({reject:s,resolve:t},n)=>{e.runtime.lastError?e.runtime.lastError.message===r?t():s(new Error(e.runtime.lastError.message)):n&&n.__mozWebExtensionPolyfillReject__?s(new Error(n.message)):t(n)},u=(e,r,s,...t)=>{if(t.length<r.minArgs)throw new Error(`Expected at least ${r.minArgs} ${i(r.minArgs)} for ${e}(), got ${t.length}`);if(t.length>r.maxArgs)throw new Error(`Expected at most ${r.maxArgs} ${i(r.maxArgs)} for ${e}(), got ${t.length}`);return new Promise(((e,r)=>{const n=A.bind(null,{resolve:e,reject:r});t.push(n),s.sendMessage(...t)}))},x={devtools:{network:{onRequestFinished:m(c)}},runtime:{onMessage:m(l),onMessageExternal:m(l),sendMessage:u.bind(null,"sendMessage",{minArgs:1,maxArgs:3})},tabs:{sendMessage:u.bind(null,"sendMessage",{minArgs:2,maxArgs:3})}},d={clear:{minArgs:1,maxArgs:1},get:{minArgs:1,maxArgs:1},set:{minArgs:1,maxArgs:1}};return s.privacy={network:{"*":d},services:{"*":d},websites:{"*":d}},g(e,x,s)};e.exports=s(chrome)}else e.exports=globalThis.browser},void 0===(t=s.apply(r,[e]))||(e.exports=t)}},r={};!function s(t){var n=r[t];if(void 0!==n)return n.exports;var i=r[t]={exports:{}};return e[t].call(i.exports,i,i.exports,s),i.exports}(8136)})();
`

**Comment by johman10** [comment]
Thanks for the information @darkman7hr!

It seems to be because the context is not what I expect it to be within the background.ts file. This can easily be fixed. I will create a fix sometime soon.

**Comment by darkman7hr** [comment]
Looking forward to it. Tnx :)

**Comment by johman10** [comment]
@darkman7hr could you pull the latests version and try again. At least for me locally it seems to work.

**Comment by johman10** [comment]
I didn't get a follow up so I'm closing this issue until someone else notices the same.

**Comment by darkman7hr** [comment]
Hi, sorry for delay,,, been heck of the time, had serious car accident and a lot of fuss....
I tried it this moment.. Token still cannot be saved, at least that what it says, but when I refrest - it's there! But no messages comes thru ? I use https://ntfy.jezgra.net:8444 which has a valid cert and everything. (my server)

**Comment by johman10** [comment]
Sorry to hear about your troubles @darkman7hr and thank you for validating.

I will reopen and reasses this at some point. Though I can't guarantee a timeline here (many other side project and a full time job as well). ;)

**Comment by darkman7hr** [comment]
maybe you could try using https://ntfy.jezgra.net:8444 server.. I added user ntfydev with password ntfydev and token for it is: tk_23j2czzbf9oqn8s3lx7j7j88bmtpb

**Comment by johman10** [comment]
I was able to connect with this configuration with the latest version from master.
![image](https://github.com/johman10/ntfy-browser/assets/5371454/d5f1fbe1-3059-4e97-a5f1-ed244cc2234d)

Can you make sure you're running the latest version and that you configuration is correct?

**Comment by darkman7hr** [comment]
im using topic with password , could that be a problem?
![Screenshot_20240224_154116](https://github.com/johman10/ntfy-browser/assets/8606499/fb46d05e-723d-4c16-8e18-8eff371a57d4)

**Comment by johman10** [comment]
@darkman7hr did you put the password in the token field? I'm sorry, but that's currently not supported. The only authorization method I added until now is the token version.

Could you try to use the token version and see if you can get it to work?

**Comment by darkman7hr** [comment]
no, just token. But does it matter that topic is under password?

**Comment by johman10** [comment]
> no, just token. But does it matter that topic is under password?

Aha, like that. That shouldn't matter, I have the same server setup and it works for me, also the error message you posted earlier is indicating that we can't read the key `getTopicQuery` from the context (`this`).

Can you please double check again that you're running the latest version by pulling and building the extension and then perhaps reinstalling?

**Comment by darkman7hr** [comment]
Hm. I deleted users, re-added. Nothing. Git cloned, built, dev inserted into chrome.
One question, what OS are you using?
I'm using slackware linux.. I havent tried windows (not sure how compiling goes there)

**Comment by darkman7hr** [comment]
well, this is weird.. I know problem now.. I'm using root acc .. I guess sand-box option to run chrome is somehow messing with options save.. tried it in normal user and it works. thank you, sry for hustle :)

**Comment by johman10** [comment]
Interesting! Glad you figured it out and thanks being engaged on this! I will close this issue now.
