### ISSUE TITLE
Getting `undefined` errors

### ISSUE THREAD

**Issue by nwithan8** [johman10/ntfy-browser#2]
Error pops up whenever I try to save settings:

<img width="692" alt="image" src="https://github.com/johman10/ntfy-browser/assets/17054780/78d12ebd-31d0-47f5-ac52-156a7cc2d435">

Tried fixing it by removing the undefined `this` reference, but it just popped up again downstream. Seems the instance of `TopicSubscriptionManager` is not initialized.

**Comment by johman10** [comment]
I think this is a duplicate of https://github.com/johman10/ntfy-browser/issues/1.

**Comment by johman10** [comment]
Please also note that since I started this project ntfy has started to support a PWA. Which is actually quite a good alternative to this.

There might be some small things where this extension can still shine, but I will probably not be super active in maintaining this project as of now.

**Comment by johman10** [comment]
@nwithan8 please pull the latest changes and try again. For me it seems to working locally.

**Comment by nwithan8** [comment]
Seems to be working. A bit confusing that opening the popup on the extension is just the "Soon this..." warning rather than a summary of the message, but I indeed get notified (actually get double notified, once from the website via built-in Chrome notifications, and once via the extension). Saving settings seems to return an error some times, but stepping through the code, it might just be a hiccup with my personal server.

Glad this is still getting worked on!

**Comment by nwithan8** [comment]
> Seems to be working. A bit confusing that opening the popup on the extension is just the "Soon this..." warning rather than a summary of the message, but I indeed get notified (actually get double notified, once from the website via built-in Chrome notifications, and once via the extension). Saving settings seems to return an error some times, but stepping through the code, it might just be a hiccup with my personal server.
> 
> Glad this is still getting worked on!

UPDATE: It seems like the cache on the settings page causes saving the settings to fail. If you clear the cache on the site (with Dev Tools open, hold refresh button and select Hard Reload), the settings can be saved.

**Comment by johman10** [comment]
> UPDATE: It seems like the cache on the settings page causes saving the settings to fail. If you clear the cache on the site (with Dev Tools open, hold refresh button and select Hard Reload), the settings can be saved.

@nwithan8 was this like a one time thing or do you see this happen consistently? I can't really reproduce this.

**Comment by nwithan8** [comment]
@johman10 it's consistent
